"""Main Flask application for Spendsight."""
from flask import Flask, render_template, request, jsonify, redirect, url_for, flash
from werkzeug.utils import secure_filename
import os
import secrets
from pathlib import Path
from backend.config import Config
from backend.parsers.chase_parser import ChaseParser
from backend.parsers.discover_parser import DiscoverParser
from backend.sheets.sheets_client import SheetsClient
from backend.analytics.categorizer import TransactionCategorizer
from backend.analytics.insights import InsightsGenerator
from backend.analytics.expense_classifier import ExpenseClassifier
from backend.models.category_rule import rule_engine, CategoryRule
from backend.models.exclusion_rule import exclusion_engine, ExclusionRule

# Initialize Flask app
app = Flask(__name__, 
            template_folder='../frontend/templates',
            static_folder='../frontend/static')
app.config.from_object(Config)

# Initialize directories
Config.init_app()

# Global storage for transactions (in production, use a database)
all_transactions = []

def needs_setup():
    """Check if the application needs initial setup."""
    env_file = Path(__file__).resolve().parent.parent / '.env'
    
    # Check if .env exists
    if not env_file.exists():
        return True
    
    # Check if Google Sheets ID is configured
    if not Config.GOOGLE_SHEETS_ID or Config.GOOGLE_SHEETS_ID.strip() == '':
        return True
    
    # Check if credentials file exists
    if not Config.GOOGLE_CREDENTIALS_PATH.exists():
        return True
    
    return False

def write_env_file(sheet_id, credentials_path='credentials.json', secret_key=None):
    """Write the .env file with configuration."""
    env_file = Path(__file__).resolve().parent.parent / '.env'
    
    # Generate secret key if not provided
    if not secret_key or secret_key.strip() == '':
        secret_key = secrets.token_hex(32)
    
    env_content = f"""# Spendsight Environment Configuration
# Auto-generated by setup wizard

# Google Sheets Configuration
GOOGLE_SHEETS_ID={sheet_id}
GOOGLE_CREDENTIALS_PATH={credentials_path}

# Flask Configuration
FLASK_SECRET_KEY={secret_key}
FLASK_ENV=development
FLASK_DEBUG=True

# Upload Configuration
UPLOAD_FOLDER=data/uploads
MAX_CONTENT_LENGTH=16777216

# Port Configuration
PORT=5000
"""
    
    env_file.write_text(env_content, encoding='utf-8')
    return True

def allowed_file(filename):
    """Check if file extension is allowed."""
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in Config.ALLOWED_EXTENSIONS

def is_duplicate_transaction(new_transaction, existing_transactions):
    """Check if a transaction already exists based on date, description, and amount."""
    for existing in existing_transactions:
        # Check if all key fields match
        if (existing.transaction_date == new_transaction.transaction_date and
            existing.description == new_transaction.description and
            abs(existing.amount - new_transaction.amount) < 0.01 and  # Float comparison tolerance
            existing.bank == new_transaction.bank):
            return True
    return False

def filter_duplicates(new_transactions, existing_transactions):
    """Filter out duplicate transactions and return unique ones with duplicate count."""
    unique_transactions = []
    duplicate_count = 0
    
    for new_tx in new_transactions:
        if is_duplicate_transaction(new_tx, existing_transactions):
            duplicate_count += 1
        else:
            unique_transactions.append(new_tx)
    
    return unique_transactions, duplicate_count

@app.before_request
def check_setup():
    """Redirect to setup if configuration is incomplete."""
    # Skip check for static files and setup routes
    setup_endpoints = ['setup', 'setup_submit', 'upload_credentials', 'check_credentials', 'restart_server']
    if request.endpoint and (request.endpoint.startswith('static') or 
                             request.endpoint in setup_endpoints):
        return None
    
    # Check if setup is needed
    if needs_setup():
        return redirect(url_for('setup'))

@app.route('/setup')
def setup():
    """Initial setup wizard."""
    # Check if credentials already exist
    creds_exist = Config.GOOGLE_CREDENTIALS_PATH.exists()
    return render_template('setup.html', credentials_exist=creds_exist)

@app.route('/setup/upload-credentials', methods=['POST'])
def upload_credentials():
    """Handle credentials JSON file upload."""
    if 'credentials_file' not in request.files:
        return jsonify({'success': False, 'error': 'No file uploaded'}), 400
    
    file = request.files['credentials_file']
    
    if file.filename == '':
        return jsonify({'success': False, 'error': 'No file selected'}), 400
    
    # Check file extension
    if not file.filename.endswith('.json'):
        return jsonify({'success': False, 'error': 'Please upload a JSON file'}), 400
    
    try:
        # Save to project root as credentials.json
        project_root = Path(__file__).resolve().parent.parent
        credentials_path = project_root / 'credentials.json'
        file.save(str(credentials_path))
        
        return jsonify({'success': True, 'message': 'Credentials uploaded successfully'})
    except Exception as e:
        return jsonify({'success': False, 'error': str(e)}), 500

@app.route('/setup/check-credentials')
def check_credentials():
    """Check if credentials file exists."""
    exists = Config.GOOGLE_CREDENTIALS_PATH.exists()
    return jsonify({'exists': exists})

@app.route('/setup/submit', methods=['POST'])
def setup_submit():
    """Handle setup form submission."""
    sheet_id = request.form.get('sheet_id', '').strip()
    
    # Validate sheet ID
    if not sheet_id:
        flash('Please provide a Google Sheet ID', 'error')
        return redirect(url_for('setup'))
    
    # Check if credentials file exists
    if not Config.GOOGLE_CREDENTIALS_PATH.exists():
        flash('Please upload your credentials.json file first', 'error')
        return redirect(url_for('setup'))
    
    # Write .env file
    try:
        write_env_file(sheet_id, 'credentials.json')
        # Return the complete page - it will trigger a restart
        return render_template('setup_complete.html', sheet_id=sheet_id)
    except Exception as e:
        flash(f'Error during setup: {str(e)}', 'error')
        return redirect(url_for('setup'))

@app.route('/setup/restart', methods=['POST'])
def restart_server():
    """Restart the server to apply new configuration."""
    import sys
    import subprocess
    
    def restart():
        """Restart the Flask server."""
        import time
        time.sleep(1)  # Brief delay to send response
        python = sys.executable
        subprocess.Popen([python, 'run.py'], cwd=Path(__file__).resolve().parent.parent)
        os._exit(0)
    
    import threading
    threading.Thread(target=restart).start()
    
    return jsonify({'status': 'restarting'})

@app.route('/')
def index():
    """Home page with interactive dashboard."""
    # If no transactions exist, redirect to upload page
    if len(all_transactions) == 0:
        return redirect(url_for('upload'))
    
    expense_transactions = [t for t in all_transactions if t.is_expense]
    
    # Get analytics data for the interactive dashboard
    categories = TransactionCategorizer.categorize_by_spending(expense_transactions)
    monthly_trends = TransactionCategorizer.monthly_trends(all_transactions)
    weekly_spending = TransactionCategorizer.weekly_spending(all_transactions)
    daily_spending = TransactionCategorizer.daily_spending(all_transactions, days=30)
    day_of_week = TransactionCategorizer.day_of_week_analysis(all_transactions)
    spending_by_bank = TransactionCategorizer.spending_by_bank(all_transactions)
    statistics = TransactionCategorizer.get_statistics(all_transactions)
    
    # Enhanced classification data
    budget_health = ExpenseClassifier.get_budget_health(all_transactions)
    classification = ExpenseClassifier.analyze_by_dimension(all_transactions)
    
    # Calculate totals
    total_spent = sum(abs(t.amount) for t in all_transactions if t.is_expense)
    total_income = sum(t.amount for t in all_transactions if t.is_income)
    
    return render_template('index.html',
                         categories=categories,
                         monthly_trends=monthly_trends,
                         weekly_spending=weekly_spending,
                         daily_spending=daily_spending,
                         day_of_week=day_of_week,
                         spending_by_bank=spending_by_bank,
                         statistics=statistics,
                         total_spent=total_spent,
                         total_income=total_income,
                         category_colors=TransactionCategorizer.CATEGORY_COLORS,
                         budget_health=budget_health,
                         classification=classification)

@app.route('/upload', methods=['GET', 'POST'])
def upload():
    """Upload CSV file page."""
    if request.method == 'POST':
        # Check if file was uploaded
        if 'file' not in request.files:
            flash('No file selected', 'error')
            return redirect(request.url)
        
        file = request.files['file']
        bank = request.form.get('bank')
        
        if file.filename == '':
            flash('No file selected', 'error')
            return redirect(request.url)
        
        if not bank or bank not in ['chase', 'discover']:
            flash('Please select a bank', 'error')
            return redirect(request.url)
        
        if file and allowed_file(file.filename):
            # Save file
            filename = secure_filename(file.filename)
            filepath = Config.UPLOAD_FOLDER / filename
            file.save(str(filepath))
            
            try:
                # Parse based on bank
                if bank == 'chase':
                    transactions = ChaseParser.parse(str(filepath))
                    summary = ChaseParser.get_summary(transactions)
                else:  # discover
                    transactions = DiscoverParser.parse(str(filepath))
                    summary = DiscoverParser.get_summary(transactions)
                
                # Filter out duplicate transactions
                unique_transactions, duplicate_count = filter_duplicates(transactions, all_transactions)
                
                if duplicate_count > 0:
                    flash(f'Skipped {duplicate_count} duplicate transaction(s).', 'info')
                
                # Apply sweep/exclusion rules to filter out unwanted transactions
                unique_transactions, swept_count = exclusion_engine.filter_new_transactions(unique_transactions)
                
                if swept_count > 0:
                    flash(f'Swept {swept_count} transaction(s) based on your sweep rules.', 'info')
                
                # Apply category rules to new transactions
                rule_engine.apply_to_all(unique_transactions)
                
                # Add to global storage
                all_transactions.extend(unique_transactions)
                
                # Sync to Google Sheets (only sync unique/new transactions)
                try:
                    sheets_client = SheetsClient()
                    if sheets_client.is_connected():
                        if len(unique_transactions) > 0:
                            sync_result = sheets_client.sync_transactions(unique_transactions)
                        sheets_client.create_monthly_summary(all_transactions)
                        
                        if 'error' in sync_result:
                            flash(f'Warning: {sync_result["error"]}', 'warning')
                        else:
                            flash(f'Synced {sync_result["synced_count"]} transactions to Google Sheets!', 'success')
                    else:
                        flash('Warning: Google Sheets not configured. Transactions saved locally only.', 'warning')
                except Exception as e:
                    flash(f'Warning: Could not sync to Google Sheets: {str(e)}', 'warning')
                
                if len(unique_transactions) > 0:
                    flash(f'Successfully uploaded {len(unique_transactions)} new transaction(s) from {bank.title()}!', 'success')
                elif duplicate_count > 0:
                    flash(f'All {duplicate_count} transaction(s) from {bank.title()} were already in the system.', 'info')
                return redirect(url_for('index'))
                
            except Exception as e:
                flash(f'Error parsing CSV: {str(e)}', 'error')
                return redirect(request.url)
        else:
            flash('Invalid file type. Please upload a CSV file.', 'error')
            return redirect(request.url)
    
    return render_template('upload.html')

@app.route('/api/transactions')
def api_transactions():
    """API endpoint to get all transactions."""
    transactions_data = [t.to_dict() for t in all_transactions]
    return jsonify(transactions_data)

@app.route('/api/insights')
def api_insights():
    """API endpoint to get insights."""
    insights = InsightsGenerator.generate_insights(all_transactions)
    return jsonify(insights)

@app.route('/api/categories')
def api_categories():
    """API endpoint to get category breakdown."""
    expense_transactions = [t for t in all_transactions if t.is_expense]
    categories = TransactionCategorizer.categorize_by_spending(expense_transactions)
    return jsonify(categories)

@app.route('/api/trends')
def api_trends():
    """API endpoint to get monthly trends."""
    trends = TransactionCategorizer.monthly_trends(all_transactions)
    return jsonify(trends)

@app.route('/api/weekly-spending')
def api_weekly_spending():
    """API endpoint for weekly spending data."""
    data = TransactionCategorizer.weekly_spending(all_transactions)
    return jsonify(data)

@app.route('/api/daily-spending')
def api_daily_spending():
    """API endpoint for daily spending data."""
    days = request.args.get('days', 30, type=int)
    data = TransactionCategorizer.daily_spending(all_transactions, days=days)
    return jsonify(data)

@app.route('/api/day-of-week')
def api_day_of_week():
    """API endpoint for day of week analysis."""
    data = TransactionCategorizer.day_of_week_analysis(all_transactions)
    return jsonify(data)

@app.route('/api/spending-by-bank')
def api_spending_by_bank():
    """API endpoint for spending by bank."""
    data = TransactionCategorizer.spending_by_bank(all_transactions)
    return jsonify(data)

@app.route('/api/velocity')
def api_velocity():
    """API endpoint for spending velocity metrics."""
    data = TransactionCategorizer.spending_velocity(all_transactions)
    return jsonify(data)

@app.route('/api/category-trends')
def api_category_trends():
    """API endpoint for category trends over time."""
    data = TransactionCategorizer.category_trends(all_transactions)
    return jsonify(data)

@app.route('/api/statistics')
def api_statistics():
    """API endpoint for statistical metrics."""
    data = TransactionCategorizer.get_statistics(all_transactions)
    return jsonify(data)

@app.route('/api/chart-data')
def api_chart_data():
    """Combined API endpoint for all chart data."""
    expense_transactions = [t for t in all_transactions if t.is_expense]
    categories = TransactionCategorizer.categorize_by_spending(expense_transactions)
    
    return jsonify({
        'categories': categories,
        'monthly_trends': TransactionCategorizer.monthly_trends(all_transactions),
        'weekly_spending': TransactionCategorizer.weekly_spending(all_transactions),
        'day_of_week': TransactionCategorizer.day_of_week_analysis(all_transactions),
        'spending_by_bank': TransactionCategorizer.spending_by_bank(all_transactions),
        'velocity': TransactionCategorizer.spending_velocity(all_transactions),
        'statistics': TransactionCategorizer.get_statistics(all_transactions),
        'category_colors': TransactionCategorizer.CATEGORY_COLORS
    })


# =========================================================================
# ENHANCED CLASSIFICATION API ENDPOINTS
# =========================================================================

@app.route('/api/classification')
def api_classification():
    """API endpoint for multi-dimensional expense classification analysis."""
    analysis = ExpenseClassifier.analyze_by_dimension(all_transactions)
    return jsonify(analysis)

@app.route('/api/budget-health')
def api_budget_health():
    """API endpoint for 50/30/20 budget health analysis."""
    health = ExpenseClassifier.get_budget_health(all_transactions)
    return jsonify(health)

@app.route('/api/subscriptions')
def api_subscriptions():
    """API endpoint for subscription analysis."""
    subscriptions = ExpenseClassifier.get_subscription_summary(all_transactions)
    return jsonify(subscriptions)

@app.route('/api/reduction-opportunities')
def api_reduction_opportunities():
    """API endpoint for spending reduction opportunities."""
    opportunities = ExpenseClassifier.get_reduction_opportunities(all_transactions)
    return jsonify(opportunities)

@app.route('/api/expense-types')
def api_expense_types():
    """API endpoint for fixed vs variable expense breakdown."""
    analysis = ExpenseClassifier.analyze_by_dimension(all_transactions)
    return jsonify(analysis.get('by_expense_type', {}))

@app.route('/api/necessity')
def api_necessity():
    """API endpoint for needs vs wants vs savings breakdown."""
    analysis = ExpenseClassifier.analyze_by_dimension(all_transactions)
    return jsonify(analysis.get('by_necessity', {}))

@app.route('/api/budget-categories')
def api_budget_categories():
    """API endpoint for high-level budget category breakdown."""
    analysis = ExpenseClassifier.analyze_by_dimension(all_transactions)
    return jsonify(analysis.get('by_budget_category', {}))

@app.route('/api/transactions/filter')
def api_transactions_filter():
    """API endpoint for filtered transactions by date range, category, period, necessity, and recurrence.
    
    Supports multiple simultaneous filters - all filters are applied with AND logic.
    """
    from datetime import datetime, timedelta
    
    # Get filter parameters
    start_date = request.args.get('start_date')
    end_date = request.args.get('end_date')
    category = request.args.get('category')
    categories = request.args.getlist('categories')  # Support multiple categories
    necessity = request.args.get('necessity')
    necessities = request.args.getlist('necessities')  # Support multiple necessities
    recurrence = request.args.get('recurrence')
    recurrences = request.args.getlist('recurrences')  # Support multiple recurrences
    period_type = request.args.get('period_type')  # 'day', 'week', 'month', 'year'
    period_value = request.args.get('period_value')  # e.g., '2024-01', 'Monday', '2024-W01'
    
    filtered = all_transactions.copy()
    
    # Filter by date range
    if start_date:
        try:
            start = datetime.strptime(start_date, '%Y-%m-%d').date()
            filtered = [t for t in filtered if t.transaction_date.date() >= start]
        except ValueError:
            pass
    
    if end_date:
        try:
            end = datetime.strptime(end_date, '%Y-%m-%d').date()
            filtered = [t for t in filtered if t.transaction_date.date() <= end]
        except ValueError:
            pass
    
    # Filter by category (single or multiple)
    if category:
        filtered = [t for t in filtered if t.category == category]
    elif categories:
        filtered = [t for t in filtered if t.category in categories]
    
    # Filter by necessity (single or multiple)
    if necessity:
        filtered = [t for t in filtered if getattr(t, 'necessity', 'Unknown') == necessity]
    elif necessities:
        filtered = [t for t in filtered if getattr(t, 'necessity', 'Unknown') in necessities]
    
    # Filter by recurrence (single or multiple)
    if recurrence:
        filtered = [t for t in filtered if getattr(t, 'recurrence', 'One-time') == recurrence]
    elif recurrences:
        filtered = [t for t in filtered if getattr(t, 'recurrence', 'One-time') in recurrences]
    
    # Filter by period type
    if period_type and period_value:
        if period_type == 'month':
            # period_value format: 'YYYY-MM'
            filtered = [t for t in filtered if t.month_year == period_value]
        elif period_type == 'week':
            # period_value format: 'YYYY-MM-DD' (week start date)
            try:
                week_start = datetime.strptime(period_value, '%Y-%m-%d').date()
                week_end = week_start + timedelta(days=6)
                filtered = [t for t in filtered if week_start <= t.transaction_date.date() <= week_end]
            except ValueError:
                pass
        elif period_type == 'day':
            # period_value format: 'YYYY-MM-DD'
            try:
                day = datetime.strptime(period_value, '%Y-%m-%d').date()
                filtered = [t for t in filtered if t.transaction_date.date() == day]
            except ValueError:
                pass
        elif period_type == 'day_of_week':
            # period_value: 'Monday', 'Tuesday', etc.
            days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
            if period_value in days:
                day_index = days.index(period_value)
                filtered = [t for t in filtered if t.transaction_date.weekday() == day_index]
        elif period_type == 'year':
            # period_value format: 'YYYY'
            try:
                year = int(period_value)
                filtered = [t for t in filtered if t.transaction_date.year == year]
            except ValueError:
                pass
    
    # Sort by date descending
    filtered.sort(key=lambda t: t.transaction_date, reverse=True)
    
    # Calculate summary
    expenses = [t for t in filtered if t.is_expense]
    income = [t for t in filtered if t.is_income]
    
    return jsonify({
        'transactions': [t.to_dict() for t in filtered],
        'summary': {
            'count': len(filtered),
            'total_spent': round(sum(abs(t.amount) for t in expenses), 2),
            'total_income': round(sum(t.amount for t in income), 2),
            'expense_count': len(expenses),
            'income_count': len(income)
        }
    })

@app.route('/extra-analytics')
def extra_analytics_page():
    """Extra detailed analytics page."""
    expense_transactions = [t for t in all_transactions if t.is_expense]
    
    # Get detailed analytics
    categories = TransactionCategorizer.categorize_by_spending(expense_transactions)
    top_merchants = TransactionCategorizer.analyze_merchants(expense_transactions, top_n=10)
    recurring = TransactionCategorizer.detect_recurring(all_transactions)
    monthly_trends = TransactionCategorizer.monthly_trends(all_transactions)
    budget_recommendations = InsightsGenerator.get_budget_recommendations(all_transactions)
    
    # New enhanced analytics
    weekly_spending = TransactionCategorizer.weekly_spending(all_transactions)
    daily_spending = TransactionCategorizer.daily_spending(all_transactions, days=30)
    day_of_week = TransactionCategorizer.day_of_week_analysis(all_transactions)
    spending_by_bank = TransactionCategorizer.spending_by_bank(all_transactions)
    velocity = TransactionCategorizer.spending_velocity(all_transactions)
    category_trends = TransactionCategorizer.category_trends(all_transactions)
    top_spending_days = TransactionCategorizer.get_top_spending_days(all_transactions, top_n=10)
    statistics = TransactionCategorizer.get_statistics(all_transactions)
    
    # Enhanced classification analytics
    classification_analysis = ExpenseClassifier.analyze_by_dimension(all_transactions)
    budget_health = ExpenseClassifier.get_budget_health(all_transactions)
    subscriptions = ExpenseClassifier.get_subscription_summary(all_transactions)
    reduction_opportunities = ExpenseClassifier.get_reduction_opportunities(all_transactions)
    
    # Calculate totals
    total_spent = sum(abs(t.amount) for t in all_transactions if t.is_expense)
    total_income = sum(t.amount for t in all_transactions if t.is_income)
    
    return render_template('extra_analytics.html',
                         categories=categories,
                         top_merchants=top_merchants,
                         recurring=recurring,
                         monthly_trends=monthly_trends,
                         budget_recommendations=budget_recommendations,
                         weekly_spending=weekly_spending,
                         daily_spending=daily_spending,
                         day_of_week=day_of_week,
                         spending_by_bank=spending_by_bank,
                         velocity=velocity,
                         category_trends=category_trends,
                         top_spending_days=top_spending_days,
                         statistics=statistics,
                         total_spent=total_spent,
                         total_income=total_income,
                         category_colors=TransactionCategorizer.CATEGORY_COLORS,
                         # Enhanced classification data
                         classification_analysis=classification_analysis,
                         budget_health=budget_health,
                         subscriptions=subscriptions,
                         reduction_opportunities=reduction_opportunities)

# =========================================================================
# CATEGORY RULES API ENDPOINTS
# =========================================================================

@app.route('/api/category-rules', methods=['GET'])
def api_get_category_rules():
    """Get all category rules."""
    rules = rule_engine.get_all_rules()
    return jsonify({
        'rules': [r.to_dict() for r in rules]
    })

@app.route('/api/category-rules', methods=['POST'])
def api_create_category_rule():
    """Create a new category rule."""
    data = request.get_json()
    
    if not data:
        return jsonify({'error': 'No data provided'}), 400
    
    category = data.get('category', '').strip()
    keywords = data.get('keywords', [])
    priority = data.get('priority', 0)
    field = data.get('field', 'category').strip()
    
    if not category:
        return jsonify({'error': 'Category/value is required'}), 400
    
    if not keywords or not isinstance(keywords, list) or len(keywords) == 0:
        return jsonify({'error': 'At least one keyword is required'}), 400
    
    # Clean up keywords
    keywords = [k.strip() for k in keywords if k.strip()]
    
    if len(keywords) == 0:
        return jsonify({'error': 'At least one non-empty keyword is required'}), 400
    
    # Validate field
    allowed_fields = ['category', 'necessity', 'recurrence', 'expense_type', 'budget_category']
    if field not in allowed_fields:
        field = 'category'
    
    # Create the rule
    rule = rule_engine.add_rule(category, keywords, priority, field)
    
    # Apply rule to all existing transactions
    updated_count = rule_engine.apply_single_rule(rule, all_transactions)
    
    return jsonify({
        'success': True,
        'rule': rule.to_dict(),
        'transactions_updated': updated_count
    })

@app.route('/api/category-rules/<rule_id>', methods=['PUT'])
def api_update_category_rule(rule_id):
    """Update an existing category rule."""
    data = request.get_json()
    
    if not data:
        return jsonify({'error': 'No data provided'}), 400
    
    category = data.get('category')
    keywords = data.get('keywords')
    priority = data.get('priority')
    enabled = data.get('enabled')
    
    # Clean up keywords if provided
    if keywords is not None:
        keywords = [k.strip() for k in keywords if k.strip()]
        if len(keywords) == 0:
            return jsonify({'error': 'At least one non-empty keyword is required'}), 400
    
    rule = rule_engine.update_rule(rule_id, category, keywords, priority, enabled)
    
    if not rule:
        return jsonify({'error': 'Rule not found'}), 404
    
    # Re-apply all rules to all transactions
    rule_engine.apply_to_all(all_transactions)
    
    return jsonify({
        'success': True,
        'rule': rule.to_dict()
    })

@app.route('/api/category-rules/<rule_id>', methods=['DELETE'])
def api_delete_category_rule(rule_id):
    """Delete a category rule."""
    success = rule_engine.delete_rule(rule_id)
    
    if not success:
        return jsonify({'error': 'Rule not found'}), 404
    
    return jsonify({'success': True})

@app.route('/api/category-rules/apply-all', methods=['POST'])
def api_apply_all_rules():
    """Re-apply all category rules to all transactions."""
    updated_count = rule_engine.apply_to_all(all_transactions)
    return jsonify({
        'success': True,
        'transactions_updated': updated_count
    })

@app.route('/api/category-rules/preview', methods=['POST'])
def api_preview_rule():
    """Preview how many transactions a rule would match."""
    data = request.get_json()
    
    if not data:
        return jsonify({'error': 'No data provided'}), 400
    
    keywords = data.get('keywords', [])
    
    if not keywords or not isinstance(keywords, list):
        return jsonify({'matching_count': 0, 'matches': []})
    
    # Clean up keywords
    keywords = [k.strip().lower() for k in keywords if k.strip()]
    
    if len(keywords) == 0:
        return jsonify({'matching_count': 0, 'matches': []})
    
    # Find matching transactions
    matches = []
    for t in all_transactions:
        desc_lower = t.description.lower()
        if all(kw in desc_lower for kw in keywords):
            matches.append({
                'description': t.description,
                'current_category': t.category,
                'amount': t.amount,
                'date': t.transaction_date.strftime('%Y-%m-%d')
            })
    
    return jsonify({
        'matching_count': len(matches),
        'matches': matches[:20]  # Limit to first 20 for preview
    })


# =========================================================================
# SWEEP/EXCLUSION RULES API ENDPOINTS
# =========================================================================

@app.route('/api/sweep-rules', methods=['GET'])
def api_get_sweep_rules():
    """Get all sweep/exclusion rules."""
    rules = exclusion_engine.get_all_rules()
    return jsonify({
        'rules': [r.to_dict() for r in rules]
    })

@app.route('/api/sweep-rules', methods=['POST'])
def api_create_sweep_rule():
    """Create a new sweep rule and apply it to existing transactions."""
    global all_transactions
    
    data = request.get_json()
    
    if not data:
        return jsonify({'error': 'No data provided'}), 400
    
    keywords = data.get('keywords', [])
    
    if not keywords or not isinstance(keywords, list) or len(keywords) == 0:
        return jsonify({'error': 'At least one keyword is required'}), 400
    
    # Clean up keywords
    keywords = [k.strip() for k in keywords if k.strip()]
    
    if len(keywords) == 0:
        return jsonify({'error': 'At least one valid keyword is required'}), 400
    
    # Create the rule
    rule = exclusion_engine.add_rule(keywords)
    
    # Apply to existing transactions (sweep them away)
    all_transactions, swept_count = exclusion_engine.sweep_transactions(all_transactions)
    
    return jsonify({
        'success': True,
        'rule': rule.to_dict(),
        'swept_count': swept_count
    })

@app.route('/api/sweep-rules/<rule_id>', methods=['PUT'])
def api_update_sweep_rule(rule_id):
    """Update an existing sweep rule."""
    data = request.get_json()
    
    if not data:
        return jsonify({'error': 'No data provided'}), 400
    
    keywords = data.get('keywords')
    enabled = data.get('enabled')
    
    rule = exclusion_engine.update_rule(
        rule_id,
        keywords=keywords,
        enabled=enabled
    )
    
    if not rule:
        return jsonify({'error': 'Rule not found'}), 404
    
    return jsonify({
        'success': True,
        'rule': rule.to_dict()
    })

@app.route('/api/sweep-rules/<rule_id>', methods=['DELETE'])
def api_delete_sweep_rule(rule_id):
    """Delete a sweep rule."""
    success = exclusion_engine.delete_rule(rule_id)
    
    if not success:
        return jsonify({'error': 'Rule not found'}), 404
    
    return jsonify({'success': True})

@app.route('/api/sweep-rules/preview', methods=['POST'])
def api_preview_sweep_rule():
    """Preview how many transactions a sweep rule would match."""
    data = request.get_json()
    
    if not data:
        return jsonify({'error': 'No data provided'}), 400
    
    keywords = data.get('keywords', [])
    
    if not keywords or not isinstance(keywords, list):
        return jsonify({'match_count': 0, 'sample_matches': []})
    
    # Clean up keywords
    keywords = [k.strip() for k in keywords if k.strip()]
    
    if len(keywords) == 0:
        return jsonify({'match_count': 0, 'sample_matches': []})
    
    # Count matching transactions
    count, samples = exclusion_engine.count_matches(keywords, all_transactions)
    
    return jsonify({
        'match_count': count,
        'sample_matches': samples
    })

@app.route('/api/sweep-rules/apply-all', methods=['POST'])
def api_apply_all_sweep_rules():
    """Re-apply all sweep rules to all transactions."""
    global all_transactions
    
    all_transactions, swept_count = exclusion_engine.sweep_transactions(all_transactions)
    
    return jsonify({
        'success': True,
        'swept_count': swept_count
    })


# =========================================================================
# TRANSACTION CATEGORY UPDATE ENDPOINT
# =========================================================================

@app.route('/api/transactions/update-category', methods=['POST'])
def api_update_transaction_category():
    """Update the category of a specific transaction."""
    data = request.get_json()
    
    if not data:
        return jsonify({'error': 'No data provided'}), 400
    
    description = data.get('description')
    date = data.get('date')
    new_category = data.get('category', '').strip()
    
    if not description or not date:
        return jsonify({'error': 'Transaction description and date are required'}), 400
    
    if not new_category:
        return jsonify({'error': 'New category is required'}), 400
    
    # Find and update the transaction
    updated = False
    for t in all_transactions:
        if t.description == description and t.transaction_date.strftime('%Y-%m-%d') == date:
            t.category = new_category
            updated = True
            break
    
    if not updated:
        return jsonify({'error': 'Transaction not found'}), 404
    
    return jsonify({'success': True, 'new_category': new_category})


@app.route('/api/transactions/update-field', methods=['POST'])
def api_update_transaction_field():
    """Update any field of a specific transaction."""
    data = request.get_json()
    
    if not data:
        return jsonify({'error': 'No data provided'}), 400
    
    description = data.get('description')
    date = data.get('date')
    field = data.get('field', '').strip()
    value = data.get('value', '').strip()
    
    if not description or not date:
        return jsonify({'error': 'Transaction description and date are required'}), 400
    
    if not field:
        return jsonify({'error': 'Field name is required'}), 400
    
    # Allowed fields to update
    allowed_fields = ['category', 'necessity', 'recurrence', 'expense_type', 'budget_category']
    
    if field not in allowed_fields:
        return jsonify({'error': f'Field "{field}" is not editable'}), 400
    
    # Find and update the transaction
    updated = False
    updated_fields = {field: value}
    
    for t in all_transactions:
        if t.description == description and t.transaction_date.strftime('%Y-%m-%d') == date:
            setattr(t, field, value)
            
            # Special handling for Income: when setting to Income, update both necessity and recurrence
            if value == 'Income':
                if field == 'necessity':
                    t.recurrence = 'Income'
                    updated_fields['recurrence'] = 'Income'
                elif field == 'recurrence':
                    t.necessity = 'Income'
                    updated_fields['necessity'] = 'Income'
            # When changing away from Income, reset the other field if it was Income
            elif field in ['necessity', 'recurrence']:
                if field == 'necessity' and t.recurrence == 'Income':
                    t.recurrence = 'One-time'
                    updated_fields['recurrence'] = 'One-time'
                elif field == 'recurrence' and t.necessity == 'Income':
                    t.necessity = 'Unknown'
                    updated_fields['necessity'] = 'Unknown'
            
            updated = True
            break
    
    if not updated:
        return jsonify({'error': 'Transaction not found'}), 404
    
    return jsonify({'success': True, 'field': field, 'value': value, 'updated_fields': updated_fields})


# =========================================================================
# GOOGLE SHEETS SYNC ENDPOINT
# =========================================================================

@app.route('/api/sync-to-sheets', methods=['POST'])
def api_sync_to_sheets():
    """Manually sync all transactions to Google Sheets."""
    if len(all_transactions) == 0:
        return jsonify({'success': False, 'error': 'No transactions to sync'})
    
    try:
        sheets_client = SheetsClient()
        
        if not sheets_client.is_connected():
            return jsonify({
                'success': False, 
                'error': 'Google Sheets not configured. Please complete setup first.'
            })
        
        # Clear and re-sync all transactions
        sync_result = sheets_client.sync_transactions(all_transactions, clear_first=True)
        
        # Also update the monthly summary
        sheets_client.create_monthly_summary(all_transactions)
        
        if 'error' in sync_result:
            return jsonify({'success': False, 'error': sync_result['error']})
        
        return jsonify({
            'success': True,
            'synced_count': sync_result.get('synced_count', len(all_transactions)),
            'message': f'Successfully synced {sync_result.get("synced_count", len(all_transactions))} transactions to Google Sheets'
        })
        
    except Exception as e:
        return jsonify({'success': False, 'error': str(e)})


if __name__ == '__main__':
    app.run(
        host='0.0.0.0',
        port=Config.PORT,
        debug=Config.DEBUG
    )

