"""Main Flask application for Spendsight."""
from flask import Flask, render_template, request, jsonify, redirect, url_for, flash
from werkzeug.utils import secure_filename
import os
import secrets
from pathlib import Path
from backend.config import Config
from backend.parsers.chase_parser import ChaseParser
from backend.parsers.discover_parser import DiscoverParser
from backend.sheets.sheets_client import SheetsClient
from backend.analytics.categorizer import TransactionCategorizer
from backend.analytics.insights import InsightsGenerator
from backend.analytics.expense_classifier import ExpenseClassifier

# Initialize Flask app
app = Flask(__name__, 
            template_folder='../frontend/templates',
            static_folder='../frontend/static')
app.config.from_object(Config)

# Initialize directories
Config.init_app()

# Global storage for transactions (in production, use a database)
all_transactions = []

def needs_setup():
    """Check if the application needs initial setup."""
    env_file = Path(__file__).resolve().parent.parent / '.env'
    
    # Check if .env exists
    if not env_file.exists():
        return True
    
    # Check if Google Sheets ID is configured
    if not Config.GOOGLE_SHEETS_ID or Config.GOOGLE_SHEETS_ID.strip() == '':
        return True
    
    # Check if credentials file exists
    if not Config.GOOGLE_CREDENTIALS_PATH.exists():
        return True
    
    return False

def write_env_file(sheet_id, credentials_path='credentials.json', secret_key=None):
    """Write the .env file with configuration."""
    env_file = Path(__file__).resolve().parent.parent / '.env'
    
    # Generate secret key if not provided
    if not secret_key or secret_key.strip() == '':
        secret_key = secrets.token_hex(32)
    
    env_content = f"""# Spendsight Environment Configuration
# Auto-generated by setup wizard

# Google Sheets Configuration
GOOGLE_SHEETS_ID={sheet_id}
GOOGLE_CREDENTIALS_PATH={credentials_path}

# Flask Configuration
FLASK_SECRET_KEY={secret_key}
FLASK_ENV=development
FLASK_DEBUG=True

# Upload Configuration
UPLOAD_FOLDER=data/uploads
MAX_CONTENT_LENGTH=16777216

# Port Configuration
PORT=5000
"""
    
    env_file.write_text(env_content, encoding='utf-8')
    return True

def allowed_file(filename):
    """Check if file extension is allowed."""
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in Config.ALLOWED_EXTENSIONS

@app.before_request
def check_setup():
    """Redirect to setup if configuration is incomplete."""
    # Skip check for static files and setup routes
    setup_endpoints = ['setup', 'setup_submit', 'upload_credentials', 'check_credentials', 'restart_server']
    if request.endpoint and (request.endpoint.startswith('static') or 
                             request.endpoint in setup_endpoints):
        return None
    
    # Check if setup is needed
    if needs_setup():
        return redirect(url_for('setup'))

@app.route('/setup')
def setup():
    """Initial setup wizard."""
    # Check if credentials already exist
    creds_exist = Config.GOOGLE_CREDENTIALS_PATH.exists()
    return render_template('setup.html', credentials_exist=creds_exist)

@app.route('/setup/upload-credentials', methods=['POST'])
def upload_credentials():
    """Handle credentials JSON file upload."""
    if 'credentials_file' not in request.files:
        return jsonify({'success': False, 'error': 'No file uploaded'}), 400
    
    file = request.files['credentials_file']
    
    if file.filename == '':
        return jsonify({'success': False, 'error': 'No file selected'}), 400
    
    # Check file extension
    if not file.filename.endswith('.json'):
        return jsonify({'success': False, 'error': 'Please upload a JSON file'}), 400
    
    try:
        # Save to project root as credentials.json
        project_root = Path(__file__).resolve().parent.parent
        credentials_path = project_root / 'credentials.json'
        file.save(str(credentials_path))
        
        return jsonify({'success': True, 'message': 'Credentials uploaded successfully'})
    except Exception as e:
        return jsonify({'success': False, 'error': str(e)}), 500

@app.route('/setup/check-credentials')
def check_credentials():
    """Check if credentials file exists."""
    exists = Config.GOOGLE_CREDENTIALS_PATH.exists()
    return jsonify({'exists': exists})

@app.route('/setup/submit', methods=['POST'])
def setup_submit():
    """Handle setup form submission."""
    sheet_id = request.form.get('sheet_id', '').strip()
    
    # Validate sheet ID
    if not sheet_id:
        flash('Please provide a Google Sheet ID', 'error')
        return redirect(url_for('setup'))
    
    # Check if credentials file exists
    if not Config.GOOGLE_CREDENTIALS_PATH.exists():
        flash('Please upload your credentials.json file first', 'error')
        return redirect(url_for('setup'))
    
    # Write .env file
    try:
        write_env_file(sheet_id, 'credentials.json')
        # Return the complete page - it will trigger a restart
        return render_template('setup_complete.html', sheet_id=sheet_id)
    except Exception as e:
        flash(f'Error during setup: {str(e)}', 'error')
        return redirect(url_for('setup'))

@app.route('/setup/restart', methods=['POST'])
def restart_server():
    """Restart the server to apply new configuration."""
    import sys
    import subprocess
    
    def restart():
        """Restart the Flask server."""
        import time
        time.sleep(1)  # Brief delay to send response
        python = sys.executable
        subprocess.Popen([python, 'run.py'], cwd=Path(__file__).resolve().parent.parent)
        os._exit(0)
    
    import threading
    threading.Thread(target=restart).start()
    
    return jsonify({'status': 'restarting'})

@app.route('/')
def index():
    """Home page with interactive dashboard."""
    expense_transactions = [t for t in all_transactions if t.is_expense]
    
    # Get analytics data for the interactive dashboard
    categories = TransactionCategorizer.categorize_by_spending(expense_transactions)
    monthly_trends = TransactionCategorizer.monthly_trends(all_transactions)
    weekly_spending = TransactionCategorizer.weekly_spending(all_transactions)
    daily_spending = TransactionCategorizer.daily_spending(all_transactions, days=30)
    day_of_week = TransactionCategorizer.day_of_week_analysis(all_transactions)
    spending_by_bank = TransactionCategorizer.spending_by_bank(all_transactions)
    statistics = TransactionCategorizer.get_statistics(all_transactions)
    
    # Enhanced classification data
    budget_health = ExpenseClassifier.get_budget_health(all_transactions)
    classification = ExpenseClassifier.analyze_by_dimension(all_transactions)
    
    # Calculate totals
    total_spent = sum(abs(t.amount) for t in all_transactions if t.is_expense)
    total_income = sum(t.amount for t in all_transactions if t.is_income)
    
    return render_template('index.html',
                         categories=categories,
                         monthly_trends=monthly_trends,
                         weekly_spending=weekly_spending,
                         daily_spending=daily_spending,
                         day_of_week=day_of_week,
                         spending_by_bank=spending_by_bank,
                         statistics=statistics,
                         total_spent=total_spent,
                         total_income=total_income,
                         category_colors=TransactionCategorizer.CATEGORY_COLORS,
                         budget_health=budget_health,
                         classification=classification)

@app.route('/upload', methods=['GET', 'POST'])
def upload():
    """Upload CSV file page."""
    if request.method == 'POST':
        # Check if file was uploaded
        if 'file' not in request.files:
            flash('No file selected', 'error')
            return redirect(request.url)
        
        file = request.files['file']
        bank = request.form.get('bank')
        
        if file.filename == '':
            flash('No file selected', 'error')
            return redirect(request.url)
        
        if not bank or bank not in ['chase', 'discover']:
            flash('Please select a bank', 'error')
            return redirect(request.url)
        
        if file and allowed_file(file.filename):
            # Save file
            filename = secure_filename(file.filename)
            filepath = Config.UPLOAD_FOLDER / filename
            file.save(str(filepath))
            
            try:
                # Parse based on bank
                if bank == 'chase':
                    transactions = ChaseParser.parse(str(filepath))
                    summary = ChaseParser.get_summary(transactions)
                else:  # discover
                    transactions = DiscoverParser.parse(str(filepath))
                    summary = DiscoverParser.get_summary(transactions)
                
                # Add to global storage
                all_transactions.extend(transactions)
                
                # Sync to Google Sheets
                try:
                    sheets_client = SheetsClient()
                    if sheets_client.is_connected():
                        sync_result = sheets_client.sync_transactions(transactions)
                        sheets_client.create_monthly_summary(all_transactions)
                        
                        if 'error' in sync_result:
                            flash(f'Warning: {sync_result["error"]}', 'warning')
                        else:
                            flash(f'Synced {sync_result["synced_count"]} transactions to Google Sheets!', 'success')
                    else:
                        flash('Warning: Google Sheets not configured. Transactions saved locally only.', 'warning')
                except Exception as e:
                    flash(f'Warning: Could not sync to Google Sheets: {str(e)}', 'warning')
                
                flash(f'Successfully uploaded {len(transactions)} transactions from {bank.title()}!', 'success')
                return redirect(url_for('index'))
                
            except Exception as e:
                flash(f'Error parsing CSV: {str(e)}', 'error')
                return redirect(request.url)
        else:
            flash('Invalid file type. Please upload a CSV file.', 'error')
            return redirect(request.url)
    
    return render_template('upload.html')

@app.route('/api/transactions')
def api_transactions():
    """API endpoint to get all transactions."""
    transactions_data = [t.to_dict() for t in all_transactions]
    return jsonify(transactions_data)

@app.route('/api/insights')
def api_insights():
    """API endpoint to get insights."""
    insights = InsightsGenerator.generate_insights(all_transactions)
    return jsonify(insights)

@app.route('/api/categories')
def api_categories():
    """API endpoint to get category breakdown."""
    expense_transactions = [t for t in all_transactions if t.is_expense]
    categories = TransactionCategorizer.categorize_by_spending(expense_transactions)
    return jsonify(categories)

@app.route('/api/trends')
def api_trends():
    """API endpoint to get monthly trends."""
    trends = TransactionCategorizer.monthly_trends(all_transactions)
    return jsonify(trends)

@app.route('/api/weekly-spending')
def api_weekly_spending():
    """API endpoint for weekly spending data."""
    data = TransactionCategorizer.weekly_spending(all_transactions)
    return jsonify(data)

@app.route('/api/daily-spending')
def api_daily_spending():
    """API endpoint for daily spending data."""
    days = request.args.get('days', 30, type=int)
    data = TransactionCategorizer.daily_spending(all_transactions, days=days)
    return jsonify(data)

@app.route('/api/day-of-week')
def api_day_of_week():
    """API endpoint for day of week analysis."""
    data = TransactionCategorizer.day_of_week_analysis(all_transactions)
    return jsonify(data)

@app.route('/api/spending-by-bank')
def api_spending_by_bank():
    """API endpoint for spending by bank."""
    data = TransactionCategorizer.spending_by_bank(all_transactions)
    return jsonify(data)

@app.route('/api/velocity')
def api_velocity():
    """API endpoint for spending velocity metrics."""
    data = TransactionCategorizer.spending_velocity(all_transactions)
    return jsonify(data)

@app.route('/api/category-trends')
def api_category_trends():
    """API endpoint for category trends over time."""
    data = TransactionCategorizer.category_trends(all_transactions)
    return jsonify(data)

@app.route('/api/statistics')
def api_statistics():
    """API endpoint for statistical metrics."""
    data = TransactionCategorizer.get_statistics(all_transactions)
    return jsonify(data)

@app.route('/api/chart-data')
def api_chart_data():
    """Combined API endpoint for all chart data."""
    expense_transactions = [t for t in all_transactions if t.is_expense]
    categories = TransactionCategorizer.categorize_by_spending(expense_transactions)
    
    return jsonify({
        'categories': categories,
        'monthly_trends': TransactionCategorizer.monthly_trends(all_transactions),
        'weekly_spending': TransactionCategorizer.weekly_spending(all_transactions),
        'day_of_week': TransactionCategorizer.day_of_week_analysis(all_transactions),
        'spending_by_bank': TransactionCategorizer.spending_by_bank(all_transactions),
        'velocity': TransactionCategorizer.spending_velocity(all_transactions),
        'statistics': TransactionCategorizer.get_statistics(all_transactions),
        'category_colors': TransactionCategorizer.CATEGORY_COLORS
    })


# =========================================================================
# ENHANCED CLASSIFICATION API ENDPOINTS
# =========================================================================

@app.route('/api/classification')
def api_classification():
    """API endpoint for multi-dimensional expense classification analysis."""
    analysis = ExpenseClassifier.analyze_by_dimension(all_transactions)
    return jsonify(analysis)

@app.route('/api/budget-health')
def api_budget_health():
    """API endpoint for 50/30/20 budget health analysis."""
    health = ExpenseClassifier.get_budget_health(all_transactions)
    return jsonify(health)

@app.route('/api/subscriptions')
def api_subscriptions():
    """API endpoint for subscription analysis."""
    subscriptions = ExpenseClassifier.get_subscription_summary(all_transactions)
    return jsonify(subscriptions)

@app.route('/api/reduction-opportunities')
def api_reduction_opportunities():
    """API endpoint for spending reduction opportunities."""
    opportunities = ExpenseClassifier.get_reduction_opportunities(all_transactions)
    return jsonify(opportunities)

@app.route('/api/expense-types')
def api_expense_types():
    """API endpoint for fixed vs variable expense breakdown."""
    analysis = ExpenseClassifier.analyze_by_dimension(all_transactions)
    return jsonify(analysis.get('by_expense_type', {}))

@app.route('/api/necessity')
def api_necessity():
    """API endpoint for needs vs wants vs savings breakdown."""
    analysis = ExpenseClassifier.analyze_by_dimension(all_transactions)
    return jsonify(analysis.get('by_necessity', {}))

@app.route('/api/budget-categories')
def api_budget_categories():
    """API endpoint for high-level budget category breakdown."""
    analysis = ExpenseClassifier.analyze_by_dimension(all_transactions)
    return jsonify(analysis.get('by_budget_category', {}))

@app.route('/api/transactions/filter')
def api_transactions_filter():
    """API endpoint for filtered transactions by date range, category, or period."""
    from datetime import datetime, timedelta
    
    # Get filter parameters
    start_date = request.args.get('start_date')
    end_date = request.args.get('end_date')
    category = request.args.get('category')
    period_type = request.args.get('period_type')  # 'day', 'week', 'month', 'year'
    period_value = request.args.get('period_value')  # e.g., '2024-01', 'Monday', '2024-W01'
    
    filtered = all_transactions.copy()
    
    # Filter by date range
    if start_date:
        try:
            start = datetime.strptime(start_date, '%Y-%m-%d').date()
            filtered = [t for t in filtered if t.transaction_date.date() >= start]
        except ValueError:
            pass
    
    if end_date:
        try:
            end = datetime.strptime(end_date, '%Y-%m-%d').date()
            filtered = [t for t in filtered if t.transaction_date.date() <= end]
        except ValueError:
            pass
    
    # Filter by category
    if category:
        filtered = [t for t in filtered if t.category == category]
    
    # Filter by period type
    if period_type and period_value:
        if period_type == 'month':
            # period_value format: 'YYYY-MM'
            filtered = [t for t in filtered if t.month_year == period_value]
        elif period_type == 'week':
            # period_value format: 'YYYY-MM-DD' (week start date)
            try:
                week_start = datetime.strptime(period_value, '%Y-%m-%d').date()
                week_end = week_start + timedelta(days=6)
                filtered = [t for t in filtered if week_start <= t.transaction_date.date() <= week_end]
            except ValueError:
                pass
        elif period_type == 'day':
            # period_value format: 'YYYY-MM-DD'
            try:
                day = datetime.strptime(period_value, '%Y-%m-%d').date()
                filtered = [t for t in filtered if t.transaction_date.date() == day]
            except ValueError:
                pass
        elif period_type == 'day_of_week':
            # period_value: 'Monday', 'Tuesday', etc.
            days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
            if period_value in days:
                day_index = days.index(period_value)
                filtered = [t for t in filtered if t.transaction_date.weekday() == day_index]
        elif period_type == 'year':
            # period_value format: 'YYYY'
            try:
                year = int(period_value)
                filtered = [t for t in filtered if t.transaction_date.year == year]
            except ValueError:
                pass
    
    # Sort by date descending
    filtered.sort(key=lambda t: t.transaction_date, reverse=True)
    
    # Calculate summary
    expenses = [t for t in filtered if t.is_expense]
    income = [t for t in filtered if t.is_income]
    
    return jsonify({
        'transactions': [t.to_dict() for t in filtered],
        'summary': {
            'count': len(filtered),
            'total_spent': round(sum(abs(t.amount) for t in expenses), 2),
            'total_income': round(sum(t.amount for t in income), 2),
            'expense_count': len(expenses),
            'income_count': len(income)
        }
    })

@app.route('/transactions')
def transactions_page():
    """View all transactions."""
    return render_template('transactions.html',
                         transactions=all_transactions)

@app.route('/extra-analytics')
def extra_analytics_page():
    """Extra detailed analytics page."""
    expense_transactions = [t for t in all_transactions if t.is_expense]
    
    # Get detailed analytics
    categories = TransactionCategorizer.categorize_by_spending(expense_transactions)
    top_merchants = TransactionCategorizer.analyze_merchants(expense_transactions, top_n=10)
    recurring = TransactionCategorizer.detect_recurring(all_transactions)
    monthly_trends = TransactionCategorizer.monthly_trends(all_transactions)
    budget_recommendations = InsightsGenerator.get_budget_recommendations(all_transactions)
    
    # New enhanced analytics
    weekly_spending = TransactionCategorizer.weekly_spending(all_transactions)
    daily_spending = TransactionCategorizer.daily_spending(all_transactions, days=30)
    day_of_week = TransactionCategorizer.day_of_week_analysis(all_transactions)
    spending_by_bank = TransactionCategorizer.spending_by_bank(all_transactions)
    velocity = TransactionCategorizer.spending_velocity(all_transactions)
    category_trends = TransactionCategorizer.category_trends(all_transactions)
    top_spending_days = TransactionCategorizer.get_top_spending_days(all_transactions, top_n=10)
    statistics = TransactionCategorizer.get_statistics(all_transactions)
    
    # Enhanced classification analytics
    classification_analysis = ExpenseClassifier.analyze_by_dimension(all_transactions)
    budget_health = ExpenseClassifier.get_budget_health(all_transactions)
    subscriptions = ExpenseClassifier.get_subscription_summary(all_transactions)
    reduction_opportunities = ExpenseClassifier.get_reduction_opportunities(all_transactions)
    
    # Calculate totals
    total_spent = sum(abs(t.amount) for t in all_transactions if t.is_expense)
    total_income = sum(t.amount for t in all_transactions if t.is_income)
    
    return render_template('extra_analytics.html',
                         categories=categories,
                         top_merchants=top_merchants,
                         recurring=recurring,
                         monthly_trends=monthly_trends,
                         budget_recommendations=budget_recommendations,
                         weekly_spending=weekly_spending,
                         daily_spending=daily_spending,
                         day_of_week=day_of_week,
                         spending_by_bank=spending_by_bank,
                         velocity=velocity,
                         category_trends=category_trends,
                         top_spending_days=top_spending_days,
                         statistics=statistics,
                         total_spent=total_spent,
                         total_income=total_income,
                         category_colors=TransactionCategorizer.CATEGORY_COLORS,
                         # Enhanced classification data
                         classification_analysis=classification_analysis,
                         budget_health=budget_health,
                         subscriptions=subscriptions,
                         reduction_opportunities=reduction_opportunities)

if __name__ == '__main__':
    app.run(
        host='0.0.0.0',
        port=Config.PORT,
        debug=Config.DEBUG
    )

